spring.application.name=booking-backend

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=
spring.datasource.password=

spring.ai.google.genai.api-key=${GOOGLE_GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect